name: Python CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Lint
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 . --count --ignore=E501,W293,E302,E261,W291,W292,F401 --show-source --statistics

      - name: Deploy via Native SSH
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key
          chmod 600 private_key
          
          ssh -i private_key -p 23 -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /home/jim/arcade
            git pull origin main
            ./venv/bin/python -m pip install -r requirements.txt
            
            pkill -f "python app.py" || true
            sleep 2
            
            nohup ./venv/bin/python app.py </dev/null >server.log 2>&1 &
            disown
            sleep 1
            exit 0
          EOF
          
          rm -rf private_key